/*
 * Top Bar Promoter v1.4.1
 *
 * Copyright 2013-2020, LambertGroup
 *
 */

 (function(b){function H(a){var c=document.cookie;var b=c.indexOf(" "+a+"=");-1==b&&(b=c.indexOf(a+"="));-1==b?c=null:(b=c.indexOf("=",b)+1,a=c.indexOf(";",b),-1==a&&(a=c.length),c=unescape(c.substring(b,a)));return null!=c&&""!=c?!0:!1}function r(a){var b=!1;a=a.substr(a.length-4).toLowerCase();if(".jpg"==a||".png"==a||".gif"==a)b=!0;return b}function E(a){"_blank"==b(a).attr("data-target")?window.open(b(a).attr("data-link")):window.location=b(a).attr("data-link")}function F(a,c,e){c=b("body").css("margin-top");
 -1!=c.lastIndexOf("px")?(c=c.substr(0,c.lastIndexOf("px")),c=parseInt(c,10)+a.height,c+="px"):-1!=c.lastIndexOf("em")&&(c=c.substr(0,c.lastIndexOf("em")),c=parseInt(c,10)+.063(a.height),c+="em");b("body").css({"margin-top":c})}function C(a,c){var e=b(window).height();e=parseInt(e-a.height-10,10);c.css({height:(0<a.selectorItemsHeight&&a.selectorItemsHeight<e?a.selectorItemsHeight:e)+"px"})}function G(a,c,e,g,p,r,t,u,l){if(a.responsive){u.html("");e=b(window).width();var w=b(window).height();if(0<
 a.siteGridWidth){var x="100%";e>a.siteGridWidth&&(x=a.siteGridWidth+"px");c.css({width:x})}770>e?(a.selectorLeftPos=7,c="none"):(a.selectorLeftPos=a.selectorLeftPosOrig,c="block");g.css({display:c});t.css({left:+a.selectorLeftPos+"px"});c=600>e?"none":a.showShare?"block":"none";p.css({display:c});c=500>e?"none":"block";r.css({display:c});u.css({display:c});g=parseInt(w-a.height-10,10);l.css({height:(0<a.selectorItemsHeight&&a.selectorItemsHeight<g?a.selectorItemsHeight:g)+"px"})}}b.fn.topBarPromoter=
 function(a){a=b.extend({},b.fn.topBarPromoter.defaults,a);return this.each(function(){var c=b(this),e=c.attr("id"),g=b("<div></div>").addClass("topBarPromoter");c.wrap(g);var p=c.parent(),A=b(".topBarPromoterLogo",c),t=b(".shareIcons",c),u=b(".close_btn",c),l=b(".open_btn",c),w=b(".the_offers_selector",c);g=b(".dropDownText",c);var x=b(".dropDownArrow",c),v=b(".preview_offer",c),h=b(".the_offers_div",c),k=b(".the_offers",c),y=b("body").css("margin-top");H(e)&&0<a.cookieExpirationMinutes?p.css({display:"none"}):
 F(a,y,y);a.hideTopBarOnInit&&0<a.cookieExpirationMinutes&&(a.hideTopBarOnInit=!1);a.previewWidthOrig=a.previewWidth;a.selectorLeftPosOrig=a.selectorLeftPos;var m=navigator.userAgent.toLowerCase();if(-1!=m.indexOf("ipad")||-1!=m.indexOf("iphone")||-1!=m.indexOf("ipod")||-1!=m.indexOf("webos")||-1!=m.indexOf("android"))a.openListOnClick=!0;for(var n=a.theElements,B=n.length,z,q=0;q<B;q++)z=a.defaultLinkTarget,void 0!=n[q].link_target&&(z=n[q].link_target),z=b('<a href="javascript:void(0);"><li rel="'+
 q+'" data-preview="'+n[q].preview+'" data-link="'+n[q].link+'" data-target="'+z+'" data-dblclick="0"><div class="offerType">'+n[q].type+'</div> <div class="offerLink">'+n[q].title+"</div></li></a>"),k.append(z);var d=a.barBg;r(a.barBg)&&(d="url("+a.barBg+")");p.css({background:d});n=0;B="100%";0<a.siteGridWidth&&(n="0 auto",B=a.siteGridWidth+"px");c.css({position:"relative",width:B,height:a.height+"px",margin:n});""!=a.logo&&(A.html('<a href="'+a.logoLink+'" target="'+a.logoLinkTarget+'"><img src="'+
 a.logo+'" border="0"></a>'),A.css({top:a.logoTopPos+"px"}));w.css({width:a.selectorWidth+"px",background:a.selectorBg+"px",top:+a.selectorTopPos+"px",left:+a.selectorLeftPos+"px"});d=a.selectorBg;r(a.selectorBg)&&(d="url("+a.selectorBg+")");b("span",g).html(a.selectorText);g.css({background:d,color:a.selectorTextColorOFF,"font-size":a.selectorTextSize+"px"});g.on("mouseover",function(){b(this).css({color:a.selectorTextColorON});a.openListOnClick||(C(a,h),h.fadeIn("slow","linear",function(){!a.openListOnClick&&
 k.height()<h.height()&&h.css({height:k.height()+"px"});k.css({width:a.selectorWidth+"px"});h.css({width:a.selectorWidth+a.previewWidth+10+"px"})}))});g.on("mouseout",function(){b(this).css({color:a.selectorTextColorOFF})});g.on("click",function(){a.openListOnClick&&(C(a,h),h.fadeToggle("slow","linear"),v.html(""))});h.on("mouseleave",function(){a.openListOnClick||(C(a,h),h.fadeOut("fast","linear"),v.html(""))});d=a.selectorArrow;r(a.selectorArrow)&&(d="url("+a.selectorArrow+")");b("span",x).html(a.selectorText);
 x.css({background:d+" "+a.selectorArrowBg});k.css({top:a.selectorItemsTopPos+"px"});b("li",k).css({background:a.selectorItemBgColorOFF,"border-color":a.selectorItemBorderOFF});b(".offerLink",k).css({top:a.selectorItemTexTopPos+"px",left:a.selectorItemTexLeftPos+"px",color:a.selectorItemTextColorOFF,"font-size":a.selectorItemTextSize+"px"});b(".offerType",k).css({width:a.selectorItemTypeWidth+"px",background:a.selectorItemTypeBgColorOFF,color:a.selectorItemTypeTextColorOFF,"font-size":a.selectorItemTypeTextSize+
 "px"});b("li",k).on("click",function(){var a=b(this).attr("rel");if(-1!=m.indexOf("ipad")||-1!=m.indexOf("iphone")||-1!=m.indexOf("ipod")||-1!=m.indexOf("webos")||-1!=m.indexOf("android")){var c=b("li",k);c.each(function(){b(this).attr("rel")!=a&&b(this).attr("data-dblclick",0)});c=b(this).attr("data-dblclick");c++;b(this).attr("data-dblclick",c);1<b(this).attr("data-dblclick")&&(b(this).attr("data-dblclick",0),E(this))}else E(this)});b("li",k).on("mouseover",function(){var f=a,d=b(window).width();
 b(this).css({background:f.selectorItemBgColorON,"border-color":f.selectorItemBorderON});b(".offerLink",this).css({color:f.selectorItemTextColorON});b(".offerType",this).css({background:f.selectorItemTypeBgColorON,color:f.selectorItemTypeTextColorON});var e=f.selectorLeftPos+f.previewLeftPos+2*f.previewBorderWidth;d>c.width()&&(e+=parseInt((d-c.width())/2,10));f.previewWidth=d-e<f.previewWidthOrig?d-e-10:f.previewWidthOrig;v.css({width:f.previewWidth+"px"});v.html('<img src="'+b(this).attr("data-preview")+
 '" style="width:'+f.previewWidth+"px; border:"+f.previewBorderWidth+"px solid "+f.previewBorderColor+'">')});b("li",k).on("mouseout",function(){b(this).css({background:a.selectorItemBgColorOFF,"border-color":a.selectorItemBorderOFF});b(".offerLink",this).css({color:a.selectorItemTextColorOFF});b(".offerType",this).css({background:a.selectorItemTypeBgColorOFF,color:a.selectorItemTypeTextColorOFF})});v.css({top:a.previewTopPos+"px",left:a.previewLeftPos+"px"});t.css({display:a.showShare,top:a.shareTopPos+
 "px",right:a.shareRightPos+"px"});d=a.shareBgOFF;r(a.shareBgOFF)&&(d="url("+a.shareBgOFF+") no-repeat");b("li",t).css({background:d});b("li",t).on("mouseover",function(){d=a.shareBgON;r(a.shareBgON)&&(d="url("+a.shareBgON+") no-repeat");b(this).css({background:d})});b("li",t).on("mouseout",function(){d=a.shareBgOFF;r(a.shareBgOFF)&&(d="url("+a.shareBgOFF+") no-repeat");b(this).css({background:d})});""!=a.closeBtn&&(u.html('<a href="javascript:void(0)" class="closeLink"><img src="'+a.closeBtn+'" border="0"></a>'),
 u.css({top:a.closeBtnTopPos+"px",right:a.closeBtnRightPos+"px"}),b(".closeLink",c).on("click",function(){p.slideToggle(250);b("body").css({"margin-top":y});if(0<a.cookieExpirationMinutes){var c=a.cookieExpirationMinutes,d=new Date;d.setTime(d.getTime()+6E4*c);c=escape("showProdBar")+(null==c?"":"; expires="+d.toUTCString());document.cookie=e+"="+c}else l.slideToggle(250)}));""!=a.openBtn&&(l.html('<a href="javascript:void(0)" class="openLink"><img src="'+a.openBtn+'" border="0"></a>'),l.css({width:"100%",
 top:"0px",right:"0px",position:"fixed","border-top":"1px solid "+a.openBtnBorderColor,margin:0,padding:0,"z-index":"1119999"}),b("img",l).css({position:"absolute",right:"0px"}),b(".openLink",c).on("click",function(){p.slideToggle(250);l.slideToggle(250);F(a,y,y)}),l.detach().appendTo("body"));a.hideTopBarOnInit?(l.css({display:"none"}),b(".closeLink",c).click(),p.css({display:"none"})):l.css({display:"none"});var D=!1;b(window).on("resize",function(){a.responsive&&(!1!==D&&clearTimeout(D),D=setTimeout(function(){G(a,
 c,p,A,t,u,w,v,h)},300))});a.responsive&&G(a,c,p,A,t,u,w,v,h)})};b.fn.topBarPromoter.defaults={height:38,siteGridWidth:0,responsive:!0,hideTopBarOnInit:!1,openListOnClick:!1,logo:"preview_images/example1/logo.png",logoLink:"http://codecanyon.net/user/LambertGroup/portfolio?ref=LambertGroup",logoLinkTarget:"_blank",logoTopPos:8,barBg:"preview_images/example1/bar_pattern.jpg",defaultLinkTarget:"_self",showShare:!0,shareTopPos:7,shareRightPos:55,shareBgOFF:"preview_images/example1/social_icons/socialCircleOFF.png",
 shareBgON:"preview_images/example1/social_icons/socialCircleON.png",closeBtn:"preview_images/example1/closeBtn.png",closeBtnTopPos:9,closeBtnRightPos:8,cookieExpirationMinutes:0,openBtn:"preview_images/example1/openBtn.png",openBtnBorderColor:"#000000",previewWidth:590,previewWidthOrig:0,previewTopPos:29,previewLeftPos:300,previewBorderWidth:3,previewBorderColor:"#fe8426",selectorWidth:300,selectorTopPos:9,selectorLeftPos:140,selectorLeftPosOrig:0,selectorBg:"preview_images/example1/dropdown_pixel.png",
 selectorArrow:"preview_images/example1/dropdown_arrow.png",selectorArrowBg:"#F76C00",selectorText:"Choose An Offer",selectorTextColorOFF:"#333333",selectorTextColorON:"#F76C00",selectorTextSize:12,selectorItemsTopPos:0,selectorItemsHeight:0,selectorItemBgColorOFF:"#000000",selectorItemBgColorON:"#000000",selectorItemBorderOFF:"#797979",selectorItemBorderON:"#797979",selectorItemTexTopPos:12,selectorItemTexLeftPos:105,selectorItemTextColorOFF:"#797979",selectorItemTextColorON:"#FFFFFF",selectorItemTextSize:11,
 selectorItemTypeWidth:77,selectorItemTypeBgColorOFF:"#939393",selectorItemTypeBgColorON:"#f76c00",selectorItemTypeTextSize:10,selectorItemTypeTextColorOFF:"#000000",selectorItemTypeTextColorON:"#000000",theElements:[{title:"All-In-One Slider",type:"JQUERY",preview:"http://1.s3.envato.com/files/19756578/PREV_AllInOne.jpg",link:"http://www.responsivejqueryslider.com",link_target:"_blank"},{title:"All-In-One Slider WP",type:"WORDPRESS",preview:"http://2.s3.envato.com/files/22050325/PREV_AllInOneTouchWP.jpg",
 link:"http://www.responsivejqueryslider.com/wordpressplugin/index.html",link_target:"_blank"}]}})(jQuery);
